# Generated by Django 4.1.4 on 2022-12-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='lstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.lstate', verbose_name='State'),
        ),
    ]
