# Generated by Django 4.1.4 on 2022-12-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_batch_client_card_agent_card_client_card_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='client',
        ),
        migrations.AlterField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='cards.client'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='lstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partners', to='cards.lstate', verbose_name='State'),
        ),
    ]
