# Generated by Django 4.1.4 on 2022-12-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_batch_status_alter_batch_amount_alter_batch_batchno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='cards.client'),
        ),
    ]
