# Generated by Django 4.1.4 on 2022-12-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_batch_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='cards.client'),
        ),
    ]
