# Generated by Django 4.1.4 on 2022-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_batch_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='printed',
            field=models.BooleanField(default=0),
        ),
    ]
