# Generated by Django 4.1.4 on 2022-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_batch_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
